### ISSUE TITLE
support mvvmcross 6.4.2

### ISSUE THREAD

**Issue by bingxueyinlian** [HisCodeness/MvvmCross.Plugin.QRCode#13]
please support mvvmcross 6.4.2，because MvvmCross.Platform 5.3.2 “ has been deprecated as it is legacy and is no longer maintained”

**Comment by HisCodeness** [comment]
@bingxueyinlian Upgrade is done ;) 

You can test it with the pre-release nuget package: [https://www.nuget.org/packages/Mvx.Plugin.QrCode/1.1.0-pre](https://www.nuget.org/packages/Mvx.Plugin.QrCode/1.1.0-pre)
